    // exports.js
import './index.scss';

export {default as Core} from './src/core';
export {default as Window} from './src/window';
export {default as Desktop} from './src/desktop';
export {default as Application} from './src/application';
export {default as Notification} from './src/notification';
export {default as Notifications} from './src/notifications';
export {default as WindowBehavior} from './src/window-behavior';
export {default as Auth} from './src/auth';
export {default as Login} from './src/login';
export {default as Websocket} from './src/websocket';
export {default as CoreServiceProvider} from './src/providers/core';
export {default as DesktopServiceProvider} from './src/providers/desktop';
export {default as NotificationServiceProvider} from './src/providers/notifications';
export {default as VFSServiceProvider} from './src/providers/vfs';
export {default as AuthServiceProvider} from './src/providers/auth';
export {default as SettingsServiceProvider} from './src/providers/settings';
export {default as logger} from './src/logger';
export {default as Splash} from './src/splash';
export {default as Settings} from './src/settings';
export {default as Tray} from './src/tray';
export {default as Search} from './src/search';
export {default as Packages} from './src/packages';
export {default as Filesystem} from './src/filesystem';
export {default as Clipboard} from './src/clipboard';
export {default as Middleware} from './src/middleware';
export {BasicApplication} from './src/basic-application';
export {defaultConfiguration as configuration} from './src/config';
export {default as icon} from './src/styles/logo-blue-32x32.png';
